CREATE TABLE Audit_Log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100),
    Action_Type VARCHAR2(20),
    Table_Name VARCHAR2(100),
    Action_Date DATE
);