CREATE OR REPLACE TRIGGER TRG_PROJECT_COMPOUND
FOR INSERT OR UPDATE OR DELETE ON Project
COMPOUND TRIGGER

    v_Action VARCHAR2(20);

BEFORE STATEMENT IS
BEGIN
    IF INSERTING THEN
        v_Action := 'INSERT';
    ELSIF UPDATING THEN
        v_Action := 'UPDATE';
    ELSIF DELETING THEN
        v_Action := 'DELETE';
    END IF;
END BEFORE STATEMENT;

AFTER STATEMENT IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Project table operation: ' || v_Action);
END AFTER STATEMENT;

END TRG_PROJECT_COMPOUND;
/