CREATE TABLE Client (
    Client_ID NUMBER PRIMARY KEY,
    Client_Name VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100),
    Address VARCHAR2(200)
);

CREATE TABLE Project (
    Project_ID NUMBER PRIMARY KEY,
    Client_ID NUMBER NOT NULL,
    Project_Name VARCHAR2(100) NOT NULL,
    Start_Date DATE,
    End_Date DATE,
    Status VARCHAR2(50),
    Budget NUMBER(12,2),

    CONSTRAINT FK_Project_Client
    FOREIGN KEY (Client_ID)
    REFERENCES Client(Client_ID)
);

CREATE TABLE Engineer (
    Engineer_ID NUMBER PRIMARY KEY,
    Project_ID NUMBER NOT NULL,
    Engineer_Name VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Specialization VARCHAR2(100),

    CONSTRAINT FK_Engineer_Project
    FOREIGN KEY (Project_ID)
    REFERENCES Project(Project_ID)
);

CREATE TABLE Worker (
    Worker_ID NUMBER PRIMARY KEY,
    Project_ID NUMBER NOT NULL,
    Worker_Name VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Job_Title VARCHAR2(100),

    CONSTRAINT FK_Worker_Project
    FOREIGN KEY (Project_ID)
    REFERENCES Project(Project_ID)
);

CREATE TABLE Material (
    Material_ID NUMBER PRIMARY KEY,
    Project_ID NUMBER NOT NULL,
    Supplier_ID NUMBER,
    Material_Name VARCHAR2(100) NOT NULL,
    Quantity NUMBER NOT NULL,
    Unit_Price NUMBER(10,2),

    CONSTRAINT FK_Material_Project
    FOREIGN KEY (Project_ID)
    REFERENCES Project(Project_ID)
);

CREATE TABLE Supplier (
    Supplier_ID NUMBER PRIMARY KEY,
    Supplier_Name VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100),
    Address VARCHAR2(200)
);

ALTER TABLE Material
ADD CONSTRAINT FK_Material_Supplier
FOREIGN KEY (Supplier_ID)
REFERENCES Supplier(Supplier_ID);
CREATE TABLE Equipment (
    Equipment_ID NUMBER PRIMARY KEY,
    Project_ID NUMBER NOT NULL,
    Equipment_Name VARCHAR2(100) NOT NULL,
    Available_Quantity NUMBER NOT NULL,
    Status VARCHAR2(50),

    CONSTRAINT FK_Equipment_Project
    FOREIGN KEY (Project_ID)
    REFERENCES Project(Project_ID)
);

CREATE TABLE Payment (
    Payment_ID NUMBER PRIMARY KEY,
    Project_ID NUMBER NOT NULL,
    Payment_Date DATE,
    Amount NUMBER(12,2) NOT NULL,
    Payment_Method VARCHAR2(50),

    CONSTRAINT FK_Payment_Project
    FOREIGN KEY (Project_ID)
    REFERENCES Project(Project_ID)
);

CREATE TABLE Public_Holidays (
    Holiday_Date DATE PRIMARY KEY,
    Holiday_Name VARCHAR2(100)
);

CREATE TABLE Audit_Log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100),
    Action_Type VARCHAR2(20),
    Table_Name VARCHAR2(100),
    Action_Date DATE
);